NIFTY_100 = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","ITC.NS","SBIN.NS","BHARTIARTL.NS","KOTAKBANK.NS",
    "LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","ULTRACEMCO.NS","NESTLEIND.NS","WIPRO.NS","HCLTECH.NS",
    "POWERGRID.NS","NTPC.NS","ONGC.NS","JSWSTEEL.NS","TATASTEEL.NS",
    "BAJFINANCE.NS","BAJAJFINSV.NS","HDFCLIFE.NS","SBILIFE.NS","ADANIENT.NS",
    "ADANIPORTS.NS","GRASIM.NS","COALINDIA.NS","BRITANNIA.NS","DIVISLAB.NS",
    "DRREDDY.NS","EICHERMOT.NS","HEROMOTOCO.NS","INDUSINDBK.NS","TECHM.NS",
    "UPL.NS","CIPLA.NS","APOLLOHOSP.NS","BAJAJ-AUTO.NS",
    "TATACONSUM.NS","SHREECEM.NS","PIDILITIND.NS","HAVELLS.NS","DABUR.NS",

    # additional to reach 100
    "ICICIPRULI.NS","NAUKRI.NS","SIEMENS.NS","BANKBARODA.NS",
    "PNB.NS","CANBK.NS","IDFCFIRSTB.NS","FEDERALBNK.NS","BANDHANBNK.NS",
    "JINDALSTEL.NS","SAIL.NS","VEDL.NS","HINDALCO.NS","NMDC.NS",
    "DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS","LODHA.NS","PRESTIGE.NS",
    "IRCTC.NS","CONCOR.NS","GAIL.NS","IGL.NS","MGL.NS",
    "BIOCON.NS","LUPIN.NS","TORNTPHARM.NS","ALKEM.NS","AUROPHARMA.NS",
    "COLPAL.NS","MARICO.NS","BERGEPAINT.NS","PAGEIND.NS","TRENT.NS",
    "PAYTM.NS","NYKAA.NS","POLYCAB.NS","KEI.NS",
    "ASTRAL.NS","DEEPAKNTR.NS","PIIND.NS","SRF.NS","NAVINFLUOR.NS"
]